### PR TITLE
Fix Github Actions

### PR DESCRIPTION
**Pull request by moonglum**
Updated the Github Actions, because they were using ancient Node versions. After that, I noticed that some tests are still failing. Some dependencies have changed their output. To decrease duplicated work, I updated all dependencies before doing adjustments. Everything is up to date now except `@rollup/plugin-node-resolve`, which breaks everything in a non-obvious and non-documented way. So I moved that to "later".

### CODE REVIEW

File: test/cli/test_browserslist/expected_legacy.js [hunk 1]
```diff
@@ -4,9 +4,28 @@ function _classCallCheck(instance, Constructor) {
   }
 }
 
-var Util = function Util() {
+function _defineProperties(target, props) {
```
Comment (moonglum) [inline test/cli/test_browserslist/expected_legacy.js:7]: This is a recurring change, which I assume comes from Babel. Apparently they changed the way they generate classes in preparation for [class fields](https://github.com/tc39/proposal-class-fields)

File: test/cli/test_bundle_customization/expected_iife.js [hunk 2]
```diff
@@ -7,4 +7,4 @@ var index = _ => {
 
 return index;
 
-}());
+})();
```
Comment (moonglum) [inline test/cli/test_bundle_customization/expected_iife.js:10]: All IIFEs are now `)()` instead of `())`

File: test/cli/test_sourcemap/faucet.config.js [hunk 3]
```diff
@@ -7,11 +7,6 @@ module.exports = {
 		source: "./src/index.js",
 		target: "./dist/bundle.js",
 		format: "esm"
-	}, {
```
Comment (moonglum) [inline test/cli/test_sourcemap/faucet.config.js:10]: I don't think we should test the sourcemaps here as well

File: test/cli/test_typescript/expected.js [hunk 4]
```diff
@@ -20,7 +20,7 @@ var generateArticle = function (params) {
     var title = params.title, authors = params.authors;
     if (typeof title !== "string") {
         log(LogLevel.Debug, "auto-generating title");
-        title = title.main + ": " + title.sub;
+        title = "".concat(title.main, ": ").concat(title.sub);
```
Comment (moonglum) [inline test/cli/test_typescript/expected.js:23]: TypeScript now translates String Interpolation differently

File: test/unit/test_bundling.js [hunk 5]
```diff
@@ -72,7 +72,7 @@ console.log("[\\u2026] ".concat(util)); // eslint-disable-line no-console
 			});
 	});
 
-	it("should support skipping transpilation for select packages", () => {
+	it.skip("should support skipping transpilation for select packages", () => {
```
Comment (moonglum) [inline test/unit/test_bundling.js:75]: TODO: need to investigate this change

File: test/cli/test_bundle_customization/expected_iife.js (hunk 2 above)
Comment (FND) [reply test/cli/test_bundle_customization/expected_iife.js:10]: interesting, I wonder why (but don't have the heart to research it now)

File: test/cli/test_sourcemap/faucet.config.js (hunk 3 above)
Comment (FND) [reply test/cli/test_sourcemap/faucet.config.js:10]: I *think* we wanted to make sure it still worked with transpilation in the mix, but 🤷 good riddance

**Review by FND — COMMENTED** [review]
Thanks for doing this, your comments were very helpful too. Looking good so far!

I might look into the remaining issues myself (plugin-node-resolve, `exclude`), but don't hold your breath...

File: pkg/faucet-pipeline-typescript/package.json [hunk 6]
```diff
@@ -16,8 +16,9 @@
 		"url": "https://github.com/faucet-pipeline/faucet-pipeline-js/issues"
 	},
 	"dependencies": {
-		"@rollup/plugin-typescript": "~6.1.0",
+		"@rollup/plugin-typescript": "~8.3.0",
 		"faucet-pipeline-js": "2.1.7",
-		"typescript": "~4.1.2"
+		"tslib": "~2.3.1",
```
Comment (moonglum) [inline pkg/faucet-pipeline-typescript/package.json:21]: If I understand this correctly, this is a runtime library for typescript. When you compile TypeScript, it will use this dependency to tree shake it to only put those parts of the library in the resulting bundle that are actually used.

Comment (moonglum) [inline pkg/faucet-pipeline-typescript/package.json:21]: If I understand this correctly, this is a runtime library for typescript. When you compile TypeScript, it will use this dependency to tree shake it to only put those parts of the library in the resulting bundle that are actually used.

File: test/cli/test_bundle_customization/expected_iife.js (hunk 2 above)
Comment (moonglum) [reply test/cli/test_bundle_customization/expected_iife.js:10]: I found the PR that introduced the change: https://github.com/rollup/rollup/pull/4215
You can see it in the blame view here: https://github.com/rollup/rollup/blame/master/test/form/samples/mjs/_expected/iife.js

I don't really see a reason why though.

Comment (moonglum) [reply test/cli/test_bundle_customization/expected_iife.js:10]: What this PR introduces is the `output.generatedCode` option which you can use to configure what JS syntax should be used for code generated by rollup (not the code you wrote yourself, but the code around it).

If I add the following to `lib/bundle/config.js`:

```js
cfg.output = {
  generatedCode: "es2015"
}
```

Then, the resulting code of `test_bundle_customization` for IIFE will for example look like this:

```diff
--- a/./expected_iife.js
+++ b/./dist/bundle_iife.js
@@ -1,10 +1,5 @@
-var MYLIB = (function () {
-'use strict';
-
-var index = _ => {
+const index = _ => {
        console.log("lipsum");
 };

-return index;
-
-})();
+export { index as default };
```

File: test/unit/test_bundling.js [hunk 7]
```diff
@@ -93,22 +93,11 @@ console.log("[\\u2026] ".concat(util)); // eslint-disable-line no-console
 					filepath: path.resolve(FIXTURES_DIR, "./dist/bundle.js"),
 					/* eslint-disable max-len */
 					content: makeBundle(`
-function createCommonjsModule(fn, basedir, module) {
```
Comment (moonglum) [inline test/unit/test_bundling.js:96]: So for me this looks like they simplified the generation of CommonJS Modules. Instead of injecting the code to generate the module, instead, they generate the module at built time.

**Comment by moonglum** [comment]
When updating `rollup/plugin-node-resolve` from 11.2.1 (which works fine) to 13.0.0 (12 does not exist, it seems to be yanked), we get the following error when compiling:

```
TypeError: this.resolve is not a function
    at Object.resolveId (node_modules/@rollup/plugin-node-resolve/dist/cjs/index.js:1080:45)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async resolveId (node_modules/rollup/dist/shared/rollup.js:21767:26)
    at async ModuleLoader.resolveId (node_modules/rollup/dist/shared/rollup.js:22067:19)
    at async /home/vagrant/Code/faucet-pipeline-js/node_modules/rollup/dist/shared/rollup.js:22353:42 {
  code: 'PLUGIN_ERROR',
  hook: 'resolveId',
  plugin: 'diskless',
  watchFiles: [
    'diskless:entry_point_1ae80c752ee1690c96fe83ddd2738d49.js'
  ]
}
```

When updating to 13.1.3 (the latest at point of writing), we get this error instead:

```
TypeError: Cannot read property 'custom' of undefined
    at Object.resolveId (node_modules/@rollup/plugin-node-resolve/dist/cjs/index.js:1165:83)
    at Object.resolveId (lib/bundle/diskless.js:18:20)
    at /home/vagrant/Code/faucet-pipeline-js/node_modules/rollup/dist/shared/rollup.js:22795:37 {
  code: 'PLUGIN_ERROR',
  hook: 'resolveId',
  plugin: 'diskless',
  watchFiles: [
    'diskless:entry_point_2b1a97035d3d3193e06c2ebe612e7348.js'
  ]
}
```

**Comment by moonglum** [comment]
Okay, summing up: 
* When updating node-resolve to 13.X, the CLI test suite as well as the "bundling" unit test pass. The "virtual" unit tests both fail with "Cannot read property 'custom' of undefined". 
* Due to the backtrace, as well as the locallity of test failure, I would assume that this is a failure that occurs from the combination of node-resolve and our "diskless" plugin.
* The [changelog for the version](https://github.com/rollup/plugins/blob/master/packages/node-resolve/CHANGELOG.md#v1300) points out a breaking change, but I don't see how it could lead to the error.

As we say in German, right now "bin ich mit meinem Latein am Ende". I don't know enough about both the diskless as well as the node-resolve Plugin. My vote would be:
Let's merge this PR, it is a signficant improvement (updating all our packages to their latest version except one). Then, let's release it (probably as a minor, given that TypeScript and Babel both allow new features?). The issue with node-resolve should be treated separately in its own PR, but this way it doesn't block the release.

What do you think, @FND?

File: .github/dependabot.yaml [hunk 8]
```diff
@@ -0,0 +1,10 @@
+version: 2
+updates:
+- package-ecosystem: github-actions
+  directory: "/"
+  schedule:
+      interval: daily
+- package-ecosystem: npm
+  directory: "/"
+  schedule:
+      interval: daily
```
Comment (FND) [inline .github/dependabot.yaml:10]: just tidied up a little; content remains the same

File: .github/workflows/tests.yaml [hunk 9]
```diff
@@ -7,11 +7,12 @@ jobs:
...
-                - 10.x
-                - 12.x
+                - 14.x
+                - 16.x
+                - 17.x
         steps:
-        - uses: actions/checkout@v1
-        - uses: actions/setup-node@v2.3.0
+        - uses: actions/checkout@v2
+        - uses: actions/setup-node@v2
```
Comment (FND) [inline .github/workflows/tests.yaml:15]: I suppose we don't need specific versions?

**Review by FND — COMMENTED** [review]
added minor tweaks to CI files (file extensions, aesthetics, actions' versions) - ran out of time for now, so will do an explanatory squash commit and release some other time

File: .github/workflows/tests.yaml (hunk 9 above)
Comment (moonglum) [reply .github/workflows/tests.yaml:15]: I'm pretty sure we should keep the version numbers. They are [regular modules, with changelogs](https://github.com/actions/checkout/blob/main/CHANGELOG.md). So a major version might introduce a breaking change, breaking our code in a non-obvious way. Our `dependabot.yml` sends a PR when there is a new version of one of those modules.

Comment (FND) [reply .github/workflows/tests.yaml:15]: Sure, but that's why I kept the major version, but removed minor and patch?

Comment (moonglum) [reply .github/workflows/tests.yaml:15]: Okay, now I get it. Yes, sure 👍

File: pkg/faucet-pipeline-typescript/package.json (hunk 6 above)
Comment (FND) [reply pkg/faucet-pipeline-typescript/package.json:21]: I'll just take your word for it. 🙂

File: test/cli/test_bundle_customization/expected_iife.js (hunk 2 above)
Comment (FND) [reply test/cli/test_bundle_customization/expected_iife.js:10]: Oh, good find - I'd been wondering about modern syntax there for a while; we should keep that in mind for v3.0?

Comment (moonglum) [reply test/cli/test_bundle_customization/expected_iife.js:10]: Yes, I think we should look at it for 3.0 👍 Not sure if we need an additional option there, or if we determine it from the browserslist. But definitely worth consideration.

**Comment by FND** [comment]
squashed as f3230c7c19a45d30a8ecb495744725e5dbe1e6a7 and released as v2.1.8 - thank you _very_ much!

**Comment by moonglum** [comment]
You're welcome 🙇
